//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"
#import "DVTSourceCodeSymbolKind.h"

@class DVTSourceCodeSymbolKind, NSAttributedString, NSString;

@interface IDEIndexCompletionItem : NSObject
{
    void *_completionResult;
    NSString *_displayText;
    NSString *_displayType;
    NSString *_completionText;
    NSAttributedString *_descriptionText;
    NSString *_parentText;
    DVTSourceCodeSymbolKind *_symbolKind;
    double _priority;
    NSString *_name;
    BOOL _notRecommended;
    double _fuzzyMatchingScore;
}

//- (void).cxx_destruct;
- (void)_fillInTheRest;
@property(readonly) NSString *completionText;
- (id)description;
@property(readonly) NSAttributedString *descriptionText;
@property(readonly) NSString *displayText;
@property(readonly) NSString *displayType;
@property double fuzzyMatchingScore; // @synthesize fuzzyMatchingScore=_fuzzyMatchingScore;
- (id)initWithCompletionResult:(void *)arg1;
@property(readonly) NSString *name; // @synthesize name=_name;
@property(readonly) BOOL notRecommended;
@property(readonly, copy) NSString *parentText;
@property double priority; // @synthesize priority=_priority;
@property(readonly) DVTSourceCodeSymbolKind *symbolKind;

@end

