//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "DVTTextCompletionStrategy.h"

@class DVTDispatchLock, IDEIndexCodeCompletionContext, NSArray, NSMapTable;

//@interface IDEIndexCompletionStrategy : DVTTextCompletionStrategy
@interface IDEIndexCompletionStrategy : NSObject
{
    unsigned long long _importStatementLocation;
    BOOL _shouldInsertIncludeStatements;
    IDEIndexCodeCompletionContext *_codeCompletionContext;
    NSArray *_knownSDKs;
    NSMapTable *_optimalBuildableProductForFileCache;
    DVTDispatchLock *_buildableProductCachesLock;
    NSArray *_sourceBuildableProductProxiesCache;
}

//- (void).cxx_destruct;
- (void)addCompletionItems:(id)arg1 forAllSymbolsOfKind:(id)arg2 inIndex:(id)arg3 context:(id)arg4;
- (void)addCompletionItems:(id)arg1 forAllSymbolsOfKind:(id)arg2 matchingLanguage:(id)arg3 inIndex:(id)arg4 context:(id)arg5;
- (id)additionalCompletionItemsForDocumentLocation:(id)arg1 context:(id)arg2;
- (id)autoImportCompletionItemsForDocumentLocation:(id)arg1 fileContext:(id)arg2 completionContexts:(id)arg3;
- (id)buildableProductsForFilePath:(id)arg1;
- (id)cachedResultOfQueryForAllSymbolsOfKind:(id)arg1 inIndex:(id)arg2;
- (id)cachedResultOfQueryForAllSymbolsOfKind:(id)arg1 matchingLanguage:(id)arg2 inIndex:(id)arg3;
- (void)clearAllBuildableProductCaches:(id)arg1;
- (void)clearCacheForFileAddedOrRemoved:(id)arg1;
- (id)completionItemsForDocumentLocation:(id)arg1 context:(id)arg2 highlyLikelyCompletionItems:(id *)arg3 areDefinitive:(char *)arg4;
- (void)dealloc;
- (id)init;
- (unsigned long long)locationForImportStatementWithContext:(id)arg1 shouldInsertIncludeStatements:(char *)arg2;
- (id)optimalBuildableProductForAutoImportable:(id)arg1 inContext:(id)arg2 headerVisibility:(unsigned long long *)arg3 alreadyLinked:(char *)arg4;
- (void)prepareForDocumentLocation:(id)arg1 context:(id)arg2;
- (BOOL)shouldAddAutoImportable:(id)arg1 intoContext:(id)arg2;

@end

